name: Standard
permissions:
  contents: write
  pull-requests: write
on: push
jobs:
  standard:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run JS autofix logic
        run: node scripts/standard.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
